- name: add ChirpStack repository
  deb822_repository:
    name: chirpstack
    types: deb
    uris: https://artifacts.chirpstack.io/packages/4.x/deb
    suites: stable
    components: main
    signed_by: https://artifacts.chirpstack.io/packages/chirpstack.key

- name: upgrade installed packages
  ansible.builtin.apt:
    update_cache: 'yes'
    upgrade: 'yes'

- name: install packages
  ansible.builtin.package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - iptables-persistent
    - sudo
    - gpg
    - golang-cfssl

